name:                otter-loop
version:             0.2.0.0
license:             BSD3

description:         Please see the README on Github

dependencies:
- base >=4.7 && <5
- dequeue
- profunctors
- constraints
- containers
- mtl

library:
  default-extensions: FlexibleInstances, GADTs
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wno-unused-top-binds
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unticked-promoted-constructors
  # - -Werror
