* Zsyntax
** TODO Introduction

   - Def.: bonding language
     - atomic formulas of Zsyntax.
     - interaction operator
   - Z-conjunction
   - Z-conditional
   - Other connectives that we do not treat here, but can be added
     straighforwardly.

** TODO Controlled monotonicity
** Reasons for a different Z-conditional operator
*** TODO Reasons for different control sets
** TODO Automated deduction

   - Simple yet effective approach: linear logic + external controlset checking
   - Have the structure of the derivation same as the corresponding linear logic
     derivation. Use control sets only to drive the inference engire, either
     rejecting or accepting potential derivations.

* The Inverse Method
** TODO Multiplicative non-determinism

   "The source of [the resource management] problem is the lack of structural
   weakening and contraction, which makes even propositional linear logic
   undecidable."

   "The resource management problem in the backward direction turns out to be
   entirely absent in the forward direction."

   "Multiplicative non-determinism, which arises from multiplicative rules with
   more than one premise, for example for $\otimes R$:

   [... rule here ...]

   "Absent weakening, in the backward direction such rules must infer a division
   (into \Delta and \Delta' above) of the linear resources of the conclusion to
   distribute into the premises. Note that this kind of non-determinism does not
   exist in a forward reading, where we simply conjoin the resources of the
   premises to construct the conclusion."

*** TODO Rationale for a forward calculus
*** TODO Description of the inverse method

    "The particular forward search strategy we use is the inverse method. The
    inverse method is a generalization of resulution, that applies to a wide
    variety of logics, with very minimal requirements: a sequent calculus with
    the subformula property. The method works as follows: first, the given goal
    sequent is fixed, and initial sequents for atomic propositions that occur
    both as positive and negative subformulas of the goal sequent. Next, the
    inference rules of the logic are specialized to the subformulas of the goal
    sequent, such that the principal formula in all inference rules is a
    subformula of the goal sequent. These rules are then used to construct new
    sequents by matching the premises against previously derived sequents. New
    sequents that are not simply instances of sequents derived earlier are
    themselves then used in the inference rules to derive newer
    sequents. Eventually, assuming the search strategy is complete, either the
    goal sequent is derived, or the search space is saturated and the goal
    sequent is found to be unprovable. The inverse method is thus a member of a
    general class of /saturation-based/ search procedures."

** Forward sequent calculus
** Subformula property
* Focused derivations
** (Introduction)

   The idea, thoroughly developed in [thesis], is "to combine the inverse
   method with the notion of focused derivations. Focused derivations arose in
   the context of logic programming as a way of refining proof search into
   phases. Each phase of the search consisted either of only asynchronous steps
   where non-determinism was immaterial, or of only synchronous steps where key
   choices have to be made. Focusing was thus a way of making "big step"
   derivations: pairs of synchronous and asynchronous steps could be thought of
   as a large derived rule. [...] There derived inference rules constructed by
   focusing can also be used to do forward search in big steps. Thus, the
   intermediate results that are internal to the phases of a focused
   derivations do not have to be explicitly constructed or stored in a sequent
   database. This reduces the size of the sequent database, which is the main
   bottleneck in the inverse method. Because a focusing inverse method prover
   is able to make much larger inferences in much fewer steps, it is able to
   explore the search space much more efficiently."

** Backward focused calculus
** Backward derived rules

   Not really going to use this, but useful to understand and develop the theory
   of focused derived rules. We will adapt all of this to the forward direction
   in the next section.

** Forward derived rules

   Notice: We don't develop a forward focused calculus, but instead directly go
   by adapting the backward calculus of derived rules to the forward direction,
   and directly establishing soundness of this calculus with respect to the
   backward focused calculus.

** Focused inverse method
*** (frontier propositions)

* Search strategy
** Sequent representation
** Subsumption
** Rules and rule application
** Search procedure

* Proof terms
** Natural deduction
** (from labelled forward sequent calculus derivations to natural deduction derivations)
** Derivation terms for forward labelled sequent calculus
** Derivation term assignment for rule calculus
